### ISSUE TITLE
hanging event handlers

### ISSUE THREAD

**Issue by alexeysofin** [nameko/nameko#517] opened 2018-02-27 14:11 UTC
We are currently experiencing an issue with nameko consumers hanging forever not acking messages nor consuming more. We have three queues (prefetch_count 25 each) which are event handlers. One event handler calls tpool some times (but seems like inside tpool there are no context switching - only open/os.scandir calls and some lxml processing), other two handlers just use nameko-sqlalchemy.

All three queues have 25 unacked messages and the process is just hanging not consuming nor acking messages. After stracing these tpool threads seems like thery are just sleeping in a loop

select(0, NULL, NULL, NULL, {20, 647391}) = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {20152, 65235860}) = 0
clock_gettime(CLOCK_MONOTONIC, {20152, 65326908}) = 0
select(0, NULL, NULL, NULL, {60, 0})    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {20212, 125662883}) = 0
clock_gettime(CLOCK_MONOTONIC, {20212, 125752436}) = 0
select(0, NULL, NULL, NULL, {60, 0})    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {20272, 184288837}) = 0
clock_gettime(CLOCK_MONOTONIC, {20272, 184380661}) = 0
select(0, NULL, NULL, NULL, {60, 0})    = 0 (Timeout)
clock_gettime(CLOCK_MONOTONIC, {20332, 195832888}) = 0
clock_gettime(CLOCK_MONOTONIC, {20332, 195917909}) = 0
select(0, NULL, NULL, NULL, {60, 0}

stracing the main thread gives

recvfrom(6, 0x7f67bc13aac8, 7, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {20686, 120473825}) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP, {u32=6, u64=2086511330193309702}}) = 0
clock_gettime(CLOCK_MONOTONIC, {20686, 120606518}) = 0
clock_gettime(CLOCK_MONOTONIC, {20686, 120649753}) = 0
epoll_wait(4, [], 1023, 1000)           = 0
clock_gettime(CLOCK_MONOTONIC, {20687, 121990770}) = 0
epoll_ctl(4, EPOLL_CTL_DEL, 6, 0x7ffd7fa5f9a0) = 0
clock_gettime(CLOCK_MONOTONIC, {20687, 122235665}) = 0
clock_gettime(CLOCK_MONOTONIC, {20687, 122304991}) = 0
recvfrom(6, 0x7f67bc13aac8, 7, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {20687, 122510493}) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP, {u32=6, u64=2086511330193309702}}) = 0
clock_gettime(CLOCK_MONOTONIC, {20687, 122653462}) = 0
clock_gettime(CLOCK_MONOTONIC, {20687, 122698273}) = 0
epoll_wait(4, ^Cstrace: Process 1810 detached

6 descriptor is amqp connection

The worst problem is that it happens sporadically and we have no idea how to reproduce it.

The log file shows and error 

`
Traceback (most recent call last):
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/hubs/hub.py", line 458, in fire_timers
    timer()
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/hubs/timer.py", line 58, in __call__
    cb(*args, **kw)
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/semaphore.py", line 147, in _do_acquire
    waiter.switch()
greenlet.error: cannot switch to a different thread
`

about at the same time the consumers started hanging. But there is no information about from where the trace came.

We are using

nameko==2.8.4
eventlet==0.21.0

**Comment by mattbennett** [comment] 2018-02-27 15:30
You may be able to figure out what the greenthreads are doing by printing their stack traces. If you [backdoor](https://groups.google.com/d/msg/nameko-dev/7Wt49pPrLz8/NdAl9vKRBgAJ) into the process, you can access the currently running managed and worker threads via the container.

Looking at their current stack may give you an idea what they're waiting for.

It looks like your queue consumer thread is waiting to receive data and not getting any, which makes sense if you're already holding max unacked messages. So I would start by trying to figure out what the worker threads are doing, and why they've not finished and acked their messages.

The "cannot switch to a different thread" message is suspicious. Whatever caused it may have broken the eventlet scheduler.

**Comment by alexeysofin** [comment] 2018-02-27 18:38
@mattbennett I managed to reproduce the issue, but the problem seems to have bad side-effects. What I did was dispatching a lot of events, and then dd from /dev/zero to a file until there is no space left on device (we are running nameko under supervisor). So when I am printing the tracebacks of all greenlets, 

```import gc
import traceback
from greenlet import greenlet
for ob in gc.get_objects():
    if not isinstance(ob, greenlet):
        continue
    if not ob:
        continue
    print(''.join(traceback.format_stack(ob.gr_frame)))
```

they are all stuck on self.greenlet.switch()

Here is an example:

```File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/greenthread.py", line 218, in main
    result = function(*args, **kwargs)
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/nameko/containers.py", line 393, in _run_worker
    result = method(*worker_ctx.args, **worker_ctx.kwargs)
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/ingest/base/retry.py", line 72, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/ingest/base/retry.py", line 72, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/ingest/release_manager/main/service.py", line 198, in handle_delivery_arrived
    delivery_handler.parse, release_uri)
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/tpool.py", line 117, in execute
    rv = e.wait()
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/event.py", line 121, in wait
    return hubs.get_hub().switch()
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/hubs/hub.py", line 295, in switch
    return self.greenlet.switch()
```

Another interesting thing I noticed is that inside a tpool there is a context switch which is caused by datetime.strptime function 

```d = datetime.strptime(duration, frm)
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 313, in _strptime
    with _cache_lock:
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/semaphore.py", line 129, in __enter__
    self.acquire()
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/semaphore.py", line 115, in acquire
    hubs.get_hub().switch()
  File "/home/dev1-irm/.venv/lib/python3.5/site-packages/eventlet/hubs/hub.py", line 295, in switch
    return self.greenlet.switch()
```

But I can not understand what is actually causing a hub to stop processing greenlets. At this time there is no "cannot switch to a different thread" log message.

My question is if context switch inside a tpool must always trigger that error? If yes, why sometimes greenlets do not block?

And another question is how do I find out the actual cause why greenlets are stuck?

**Comment by mattbennett** [comment] 2018-03-04 09:29
I'm confused. Why did you choose to consume all the disk space to reproduce the issue? Couldn't this be causing a completely different problem?

From what I understand of tpool, it's intended to wrap non-green functions that would otherwise block the event loop. If the thing you're wrapping yields, why are you using the tpool?

**Comment by alexeysofin** [comment] 2018-03-04 13:34
@mattbennett sorry for a little chaotic reply :) I chose to consume all disk space because about at the same time we had hanging consumers we had "no space left on device" errors and I thought that this might be causing the problem. 

Gegarding tpool, I actually wrapped python code that seemed to have no yields but when I inspected greenlets with the help of backdoor, I noticed that strptime function uses some semaphore which is patched by eventlet and this is causing a yield. 

I agree that full disk and hanging consumers are actually separate problems and the real cause was the implicit yield from strptime. So I am going to remove tpool (and use it more wisely next time) from that part of code and give it a try.

**Comment by mattbennett** [comment] 2018-03-05 07:07
Ha, no worries. Yep, let's close this issue.

I guess the root cause is either the out of disk space error or the yield inside the tpool. You might want to check over at github.com/eventlet/eventlet whether a yield inside a tpool is expected to cause problems. Seems a bit fragile to me.

**Closed** 2018-03-05 07:35 UTC
