### ISSUE TITLE
Eventlet 0.20.0 breaks dns resolution in nameko 

### ISSUE THREAD

**Issue by rgardam** [nameko/nameko#392] opened 2016-12-20 14:00 UTC
I seem to have hit  a very strange bug running nameko inside of docker-compose 
At this point, i'm able to get around the issue, but I would like to know if eventlet or docker is doing something wrong. 

Docker: 
Version 1.12.3 (13776)
Channel: Stable
583d1b8ffe

nameko version 2.3.1

**Traceback from inside the container.**

```
[root@ba50a39f5dbb app]# nameko run --config ./cfg/nameko.yaml blah.blah.service:blahService
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/eventlet-0.20.0-py2.7.egg/eventlet/hubs/poll.py", line 115, in wait
    listener.cb(fileno)
  File "/usr/lib/python2.7/site-packages/eventlet-0.20.0-py2.7.egg/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/nameko/utils.py", line 175, in call
    return getattr(item, name)(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/nameko/messaging.py", line 191, in setup
    verify_amqp_uri(self.amqp_uri)
  File "build/bdist.linux-x86_64/egg/nameko/amqp.py", line 43, in verify_amqp_uri
    with transport.establish_connection():
  File "/usr/lib/python2.7/site-packages/kombu-4.0.2-py2.7.egg/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/lib/python2.7/site-packages/amqp-2.1.4-py2.7.egg/amqp/connection.py", line 294, in connect
    self.transport.connect()
  File "/usr/lib/python2.7/site-packages/amqp-2.1.4-py2.7.egg/amqp/transport.py", line 120, in connect
    self._connect(self.host, self.port, self.connect_timeout)
  File "/usr/lib/python2.7/site-packages/amqp-2.1.4-py2.7.egg/amqp/transport.py", line 150, in _connect
    host, port, 0, socket.SOCK_STREAM, SOL_TCP,
  File "/usr/lib/python2.7/site-packages/eventlet-0.20.0-py2.7.egg/eventlet/support/greendns.py", line 464, in getaddrinfo
    raise socket.gaierror(socket.EAI_NONAME, 'No address found')
gaierror: [Errno -2] No address found

```

The host dns resolves with a non authoritive response, but all dns functions work correctly from the container itself.

Pinning the version of eventlet to 0.16.1 seems to stop the issue from occurring. 

Is the eventlet dns client implementation known to have issues?

thanks in advance! :)
Rob

**Comment by davidszotten** [comment] 2016-12-20 14:06
eventlet 0.20 did change some dns handling, e.g. https://github.com/eventlet/eventlet/blob/master/NEWS#L4

could you post some more details? is it possible to reproduce with eventlet only (without nameko)

**Comment by rgardam** [comment] 2016-12-20 14:09
Hey, yes, I just posted a bit more.

**Comment by manfred-chebli** [comment] 2016-12-20 14:14
Hello !

We had this problem too for the last two weeks. When nameko uses the config.yml with an hostname to connect to the broker, the resolution is not handled properly, and the service cannot connect to the broker. The stack is like this:

```
Traceback (most recent call last):
File "/usr/local/bin/nameko", line 9, in <module>
  load_entry_point('nameko==2.3.2', 'console_scripts', 'nameko')()
   File "/usr/local/lib/python2.7/dist-packages/nameko/cli/main.py", line 26, in main
     args.main(args)
   File "/usr/local/lib/python2.7/dist-packages/nameko/cli/run.py", line 185, in main
     run(services, config, backdoor_port=args.backdoor_port)
   File "/usr/local/lib/python2.7/dist-packages/nameko/cli/run.py", line 132, in run
     service_runner.start()
   File "/usr/local/lib/python2.7/dist-packages/nameko/runners.py", line 67, in start
     SpawningProxy(self.containers).start()
   File "/usr/local/lib/python2.7/dist-packages/nameko/utils.py", line 180, in spawning_method
     return list(pool.imap(call, self._items))
   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenpool.py", line 238, in next
     val = self.waiters.get().wait()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 175, in wait
     return self._exit_event.wait()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/event.py", line 121, in wait
     return hubs.get_hub().switch()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 294, in switch
     return self.greenlet.switch()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 214, in main
     result = function(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/nameko/utils.py", line 175, in call
     return getattr(item, name)(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/nameko/containers.py", line 198, in start
     self.extensions.all.setup()
   File "/usr/local/lib/python2.7/dist-packages/nameko/utils.py", line 180, in spawning_method
     return list(pool.imap(call, self._items))
   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenpool.py", line 238, in next
     val = self.waiters.get().wait()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 175, in wait
     return self._exit_event.wait()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/event.py", line 121, in wait
     return hubs.get_hub().switch()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/hub.py", line 294, in switch
     return self.greenlet.switch()
   File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 214, in main
     result = function(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/nameko/utils.py", line 175, in call
     return getattr(item, name)(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/nameko/messaging.py", line 191, in setup
     verify_amqp_uri(self.amqp_uri)
   File "/usr/local/lib/python2.7/dist-packages/nameko/amqp.py", line 48, in verify_amqp_uri
     with transport.establish_connection():
   File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
     conn = self.Connection(**opts)
   File "/usr/local/lib/python2.7/dist-packages/nameko/amqp.py", line 25, in __init__
     super(ConnectionTester, self).__init__(*args, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 165, in __init__
     self.transport = self.Transport(host, connect_timeout, ssl)
   File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 186, in Transport
     return create_transport(host, connect_timeout, ssl)
   File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 299, in create_transport
     return TCPTransport(host, connect_timeout)
   File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 75, in __init__
     socket.SOCK_STREAM, SOL_TCP):
   File "/usr/local/lib/python2.7/dist-packages/eventlet/support/greendns.py", line 464, in getaddrinfo
     raise socket.gaierror(socket.EAI_NONAME, 'No address found')
 socket.gaierror: [Errno -2] No address found
 2016/12/20 14:10:59 Command exited with error: exit status 1
service exited with code 1
```

It seems the last version of kombu (> 0.4.x) requires the last version of eventlet (0.20.0), which 
To workaround, we forced kombu at version 3.0.37, and eventlet at version 0.19.0 in our requirements.

**Comment by rgardam** [comment] 2016-12-20 14:20
Ok, that makes sense.

i can see that Kombu is pinned to not use <4, but I guess this doesn't stop eventlet from using the latest

**Comment by rgardam** [comment] 2016-12-20 14:25
Do we want to reference this here? 
https://github.com/nameko/nameko/issues/378

and just close this one? 

Seems to be related.

**Comment by kooba** [comment] 2016-12-20 14:35
Hi @manfred-chebli & @rgardam have you docker "linked" your `broker` container to your service container? Or do you just rely on Docker embedded DNS server by simply using the name (`broker` in your case) of the container?

Once we've upgraded to master version of Eventlet (before they cut 0.20 release, we needed it to use a fix to HTTPS body parsing https://github.com/eventlet/eventlet/blob/master/NEWS#L8) we noticed that Docker embedded DNS name resolution does not work any more. 

Since `eventlet` vendored `dnspython` I've opened issue directly with `dnspython` here https://github.com/rthalley/dnspython/issues/219 but they said this is expected behaviour. There is a gist to reproduce the issue. 

The workaround we've employed for now is to trick `dnspython` into thinking that our container names are fully qualified domains by adding period `.` to the url. In your case it would be `amqp://user:pass@broker.:5672`

I think by using `dnspython` for dns resolution `eventlet` broke some functionality.

**Comment by davidszotten** [comment] 2016-12-20 14:36
we don't yet support kombu >=4, but we do support eventlet 0.20, see e.g. tests passing on travis for https://github.com/nameko/nameko/pull/388

**Comment by rgardam** [comment] 2016-12-20 14:40
@kooba It seems like inside of newer versions of docker-compose the link: option doesn't do what it used to do. 

Previously docker would create /etc/hosts entries, but this is not the case and it now only uses the internal dns.

Ah! ok.

**Comment by mattbennett** [comment] 2016-12-20 15:05
There are a couple of threads of conversation happening here now. Let me try to summarise:

1. Kombu 4.0 requires eventlet 0.2.0, but nameko pins kombu to 3.0.37, so this is irrelevant. #378 is not related.

2. Eventlet 0.2.0 bundles dnspython and seems to use it to monkeypatch the `socket` library's DNS functions. Unfortunately dnspython doesn't have exactly the same behaviour -- in particular, it won't resolve a fully qualified domain name without a `.` at the end if there's a search domain specified. From what I understand about DNS that's the _correct_ behaviour, but the fact that `socket.getaddrinfo` behaves differently suggests there's bug is in eventlet's assumption that they're equivalent.

**Comment by davidszotten** [comment] 2016-12-20 16:05
when/where did we conclude 1 (that kombu 4 requires eventlet 0.20)?

(agree w.r.t. 2)

**Comment by mattbennett** [comment] 2016-12-20 16:21
I took it as read from @rgardam's message above. It's not correct -- there's dependency on eventlet in kombu.

**Comment by rgardam** [comment] 2016-12-20 17:21
What I was saying is that in the nameko setup.py is only set to use greater than 0.16.1 which will install the latest. 


install_requires=[
        "eventlet>=0.16.1",
        "kombu>=3.0.1,<4",
        "mock>=1.2",
        "path.py>=6.2",
        "pyyaml>=3.10",
        "requests>=1.2.0",
        "six>=1.9.0",
        "werkzeug>=0.9",
    ],

**Comment by mattbennett** [comment] 2016-12-20 18:31
I have raised this as a bug with eventlet https://github.com/eventlet/eventlet/issues/363

In the mean time, the workarounds are:

* pin eventlet down to <0.2.0 in your application
* resolve using a strictly fully-qualified domain name (i.e. put a `.` at the end)

For the moment I think it's too restrictive to pin eventlet down in nameko itself.

**Comment by temoto** [comment] 2016-12-22 04:11
Hello.

I've noticed responsibility shifting tendency, so it's not Eventlet fault either. It's OS `getaddrinfo` that is bugged! You can always blame `libc`. :-)
`resolv.conf` docs suggest that names with strictly less than `options:ndots` must be resolved using search domains. `ndots` defaults to 1, that affects unqualified names like `broker`.

Dnspython was always providing kinda proper behavior (it forces `ndots:1` regardless of config) but Eventlet `<0.20` used system (blocking) getaddrinfo by default, unless special environment variable set. Now its resolving is always green.

I don't see a problem for Eventlet to support broken OS `getaddrinfo`, so make your pins `>=0.20.1`.

**Comment by temoto** [comment] 2016-12-22 13:36
Please try this version with fix

`pip install -U https://github.com/eventlet/eventlet/archive/f266be30f5c3ff1889e9ac3f0bad698a49d40e99.zip`

you can always revert back to your favorite with `pip install -r requirements.txt`.

**Comment by mattbennett** [comment] 2016-12-22 16:18
👍  @temoto. With the fix it works as expected.

**Comment by temoto** [comment] 2017-01-03 01:41
The fix is included in Eventlet v0.20.1 version that is already available on PyPI.
If you pinned requirements to 0.19 or installed zip from long url above, please update to eventlet==0.20.1 now.

Fly safe.

**Comment by rgardam** [comment] 2017-01-03 16:51
Thanks for the quick resolution on this! :)

**Closed** 2017-01-20 09:40 UTC

**Comment by alexander-mayr** [comment] 2019-01-23 16:00
I am having the same issue with eventlet 0.24.1 (see below). I'm not sure if it's the same issue but according to the stack trace this should be somehow related to eventlet again.
```
amqp (2.4.0)
certifi (2018.11.29)
chardet (3.0.4)
dnspython (1.16.0)
eventlet (0.24.1)
GDAL (2.1.3)
greenlet (0.4.15)
idna (2.8)
importlib-metadata (0.8)
kombu (4.2.2.post1)
mock (2.0.0)
monotonic (1.5)
nameko (2.11.0)
numpy (1.11.0)
path.py (11.5.0)
pbr (5.1.1)
pip (8.1.1)
pycurl (7.43.0)
pygobject (3.20.0)
python-apt (1.1.0b1+ubuntu0.16.4.2)
PyYAML (3.13)
requests (2.21.0)
setuptools (20.7.0)
six (1.12.0)
unattended-upgrades (0.1)
urllib3 (1.24.1)
vine (1.2.0)
Werkzeug (0.14.1)
wheel (0.29.0)
wrapt (1.11.1)
zipp (0.3.3)
7
```



> test_service_1  | Traceback (most recent call last):
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 137, in _connect
> test_service_1  |     host, port, family, socket.SOCK_STREAM, SOL_TCP)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/support/greendns.py", line 537, in getaddrinfo
> test_service_1  |     raise socket.gaierror(socket.EAI_NONAME, 'No address found')
> test_service_1  | socket.gaierror: [Errno -2] No address found
> test_service_1  | 
> test_service_1  | During handling of the above exception, another exception occurred:
> test_service_1  | 
> test_service_1  | Traceback (most recent call last):
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/poll.py", line 109, in wait
> test_service_1  |     listener.cb(fileno)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 219, in main
> test_service_1  |     result = function(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 181, in call
> test_service_1  |     return getattr(item, name)(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/messaging.py", line 226, in setup
> test_service_1  |     verify_amqp_uri(self.amqp_uri, ssl=ssl)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/amqp/utils.py", line 41, in verify_amqp_uri
> test_service_1  |     with transport.establish_connection():
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
> test_service_1  |     conn.connect()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/connection.py", line 307, in connect
> test_service_1  |     self.transport.connect()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 81, in connect
> test_service_1  |     self._connect(self.host, self.port, self.connect_timeout)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 148, in _connect
> test_service_1  |     "failed to resolve broker hostname"))
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 161, in _connect
> test_service_1  |     self.sock.connect(sa)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 265, in connect
> test_service_1  |     socket_checkerr(fd)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 51, in socket_checkerr
> test_service_1  |     raise socket.error(err, errno.errorcode[err])
> test_service_1  | ConnectionRefusedError: [Errno 111] ECONNREFUSED
> test_service_1  | Removing descriptor: 4
> test_service_1  | Traceback (most recent call last):
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 137, in _connect
> test_service_1  |     host, port, family, socket.SOCK_STREAM, SOL_TCP)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/support/greendns.py", line 537, in getaddrinfo
> test_service_1  |     raise socket.gaierror(socket.EAI_NONAME, 'No address found')
> test_service_1  | socket.gaierror: [Errno -2] No address found
> test_service_1  | 
> test_service_1  | During handling of the above exception, another exception occurred:
> test_service_1  | 
> test_service_1  | Traceback (most recent call last):
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 460, in fire_timers
> test_service_1  |     timer()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/timer.py", line 59, in __call__
> test_service_1  |     cb(*args, **kw)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/event.py", line 177, in _do_send
> test_service_1  |     waiter.throw(*exc)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 219, in main
> test_service_1  |     result = function(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 181, in call
> test_service_1  |     return getattr(item, name)(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/containers.py", line 188, in start
> test_service_1  |     self.extensions.all.setup()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 186, in spawning_method
> test_service_1  |     return list(pool.imap(call, self._items))
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenpool.py", line 244, in next
> test_service_1  |     val = self.waiters.get().wait()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 180, in wait
> test_service_1  |     return self._exit_event.wait()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/event.py", line 125, in wait
> test_service_1  |     result = hub.switch()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 297, in switch
> test_service_1  |     return self.greenlet.switch()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 219, in main
> test_service_1  |     result = function(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 181, in call
> test_service_1  |     return getattr(item, name)(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/messaging.py", line 226, in setup
> test_service_1  |     verify_amqp_uri(self.amqp_uri, ssl=ssl)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/amqp/utils.py", line 41, in verify_amqp_uri
> test_service_1  |     with transport.establish_connection():
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
> test_service_1  |     conn.connect()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/connection.py", line 307, in connect
> test_service_1  |     self.transport.connect()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 81, in connect
> test_service_1  |     self._connect(self.host, self.port, self.connect_timeout)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 148, in _connect
> test_service_1  |     "failed to resolve broker hostname"))
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 161, in _connect
> test_service_1  |     self.sock.connect(sa)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 265, in connect
> test_service_1  |     socket_checkerr(fd)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 51, in socket_checkerr
> test_service_1  |     raise socket.error(err, errno.errorcode[err])
> test_service_1  | ConnectionRefusedError: [Errno 111] ECONNREFUSED
> test_service_1  | Traceback (most recent call last):
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 137, in _connect
> test_service_1  |     host, port, family, socket.SOCK_STREAM, SOL_TCP)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/support/greendns.py", line 537, in getaddrinfo
> test_service_1  |     raise socket.gaierror(socket.EAI_NONAME, 'No address found')
> test_service_1  | socket.gaierror: [Errno -2] No address found
> test_service_1  | 
> test_service_1  | During handling of the above exception, another exception occurred:
> test_service_1  | 
> test_service_1  | Traceback (most recent call last):
> test_service_1  |   File "/usr/local/bin/nameko", line 11, in <module>
> test_service_1  |     sys.exit(main())
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/cli/main.py", line 107, in main
> test_service_1  |     args.main(args)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/cli/commands.py", line 110, in main
> test_service_1  |     main(args)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/cli/run.py", line 184, in main
> test_service_1  |     run(services, config, backdoor_port=args.backdoor_port)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/cli/run.py", line 131, in run
> test_service_1  |     service_runner.start()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/runners.py", line 66, in start
> test_service_1  |     SpawningProxy(self.containers).start()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 186, in spawning_method
> test_service_1  |     return list(pool.imap(call, self._items))
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenpool.py", line 244, in next
> test_service_1  |     val = self.waiters.get().wait()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 180, in wait
> test_service_1  |     return self._exit_event.wait()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/event.py", line 125, in wait
> test_service_1  |     result = hub.switch()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 297, in switch
> test_service_1  |     return self.greenlet.switch()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 219, in main
> test_service_1  |     result = function(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 181, in call
> test_service_1  |     return getattr(item, name)(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/containers.py", line 188, in start
> test_service_1  |     self.extensions.all.setup()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 186, in spawning_method
> test_service_1  |     return list(pool.imap(call, self._items))
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenpool.py", line 244, in next
> test_service_1  |     val = self.waiters.get().wait()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 180, in wait
> test_service_1  |     return self._exit_event.wait()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/event.py", line 125, in wait
> test_service_1  |     result = hub.switch()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/hubs/hub.py", line 297, in switch
> test_service_1  |     return self.greenlet.switch()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenthread.py", line 219, in main
> test_service_1  |     result = function(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/utils/__init__.py", line 181, in call
> test_service_1  |     return getattr(item, name)(*args, **kwargs)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/messaging.py", line 226, in setup
> test_service_1  |     verify_amqp_uri(self.amqp_uri, ssl=ssl)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/nameko/amqp/utils.py", line 41, in verify_amqp_uri
> test_service_1  |     with transport.establish_connection():
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
> test_service_1  |     conn.connect()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/connection.py", line 307, in connect
> test_service_1  |     self.transport.connect()
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 81, in connect
> test_service_1  |     self._connect(self.host, self.port, self.connect_timeout)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 148, in _connect
> test_service_1  |     "failed to resolve broker hostname"))
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/amqp/transport.py", line 161, in _connect
> test_service_1  |     self.sock.connect(sa)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 265, in connect
> test_service_1  |     socket_checkerr(fd)
> test_service_1  |   File "/usr/local/lib/python3.5/dist-packages/eventlet/greenio/base.py", line 51, in socket_checkerr
> test_service_1  |     raise socket.error(err, errno.errorcode[err])
> test_service_1  | ConnectionRefusedError: [Errno 111] ECONNREFUSED
>

**Comment by mattbennett** [comment] 2019-01-23 16:07
@alexander-mayr you will always see eventlet in the stack trace for a Nameko service (eventlet runs all the threads)

Your error is not related to DNS. It looks like Nameko cannot connect to your RabbitMQ broker.

**Comment by alexander-mayr** [comment] 2019-01-23 16:41
@mattbennett 

thank you. The stackstrace itself is rather weird as it brings "connection refused" and dns errors. I am out of the office for today but I see if I can get some more details tomorrow.

**Comment by mattbennett** [comment] 2019-01-23 16:53
Oh sorry, I missed those 'No address found' errors in the middle there.

That is a little weird. I don't understand why you'd see both `ConnectionRefusedError ` _and_ `No address found` in the same stacktrace (Did it resolve an IP address and fail to connect to it, or fail to resolve the name? They seem mutually exclusive).

Not ruling this out being the same issue. If you can debug further that would be helpful.

**Comment by alexander-mayr** [comment] 2019-01-24 07:51
@mattbennett 
This was a pebcak. Problem was solved by adding a sleep script to the container entrypoint to properly wait for the broker to startup. Sorry for the confusion.
