### ISSUE TITLE
Check for existing key

### ISSUE THREAD

**Issue by Headmaster11** [nameko/nameko#742] opened 2021-11-12 08:01 UTC
https://github.com/nameko/nameko/blob/master/nameko/rpc.py#L201
https://github.com/nameko/nameko/blob/master/nameko/rpc.py#L219

Don't you think, that here should be check for the key? It doesn't look good, when getting **key error** instead of some valid exception

**Comment by mattbennett** [comment] 2023-02-23 12:44
Closing as a duplicate of #753

**Closed by mattbennett** 2023-02-23 12:44 UTC
